export const defaultRules = {
  name: '水利工程报告',
  version: '1.0',
  pageSetup: {
    paperSize: 'A4',
    marginTop: 3.7,
    marginBottom: 3.5,
    marginLeft: 2.8,
    marginRight: 2.6,
  },
  styles: {
    heading1: {
      label: '一级标题',
      detect: { outlineLevel: 0 },
      fontCN: '黑体',
      fontEN: 'Times New Roman',
      fontSize: 16,
      bold: false,
      alignment: 'center',
      spaceBefore: 24,
      spaceAfter: 24,
      lineSpacing: 20,
      lineRule: 'exact',
      firstLineIndent: 0,
    },
    heading2: {
      label: '二级标题',
      detect: { outlineLevel: 1 },
      fontCN: '楷体',
      fontEN: 'Times New Roman',
      fontSize: 14,
      bold: true,
      alignment: 'left',
      spaceBefore: 12,
      spaceAfter: 12,
      lineSpacing: 18,
      lineRule: 'exact',
      firstLineIndent: 0,
    },
    heading3: {
      label: '三级标题',
      detect: { outlineLevel: 2 },
      fontCN: '宋体',
      fontEN: 'Times New Roman',
      fontSize: 13,
      bold: false,
      alignment: 'left',
      spaceBefore: 12,
      spaceAfter: 12,
      lineSpacing: 16,
      lineRule: 'exact',
      firstLineIndent: 0,
    },
    heading4: {
      label: '四级标题',
      detect: { outlineLevel: 3 },
      fontCN: '宋体',
      fontEN: 'Times New Roman',
      fontSize: 12,
      bold: false,
      alignment: 'left',
      spaceBefore: 12,
      spaceAfter: 12,
      lineSpacing: 15,
      lineRule: 'exact',
      firstLineIndent: 0,
    },
    body: {
      label: '正文',
      detect: { outlineLevel: -1 },
      fontCN: '宋体',
      fontEN: 'Times New Roman',
      fontSize: 13,
      bold: false,
      alignment: 'both',
      spaceBefore: 0,
      spaceAfter: 0,
      lineSpacing: 25,
      lineRule: 'exact',
      charIndent: 2,
    },
    caption: {
      label: '图表标题',
      detect: { outlineLevel: -1, pattern: '^(图|表)\\s*\\d' },
      fontCN: '黑体',
      fontEN: 'Times New Roman',
      fontSize: 10.5,
      bold: false,
      alignment: 'center',
      spaceBefore: 0,
      spaceAfter: 0,
      lineSpacing: 15,
      lineRule: 'exact',
      firstLineIndent: 0,
    },
  },
  table: {
    outerBorderWidth: 1.5,
  },
  image: {
    alignment: 'center',
    lineSpacing: 1.5,
    lineRule: 'auto',
  },
};
